version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_ans
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ans_relatorios
      POSTGRES_USER: admin  #foi fornecido a senha, apenas para fins de teste.
      POSTGRES_PASSWORD: admin
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
      - ./anexos_operadoras_csv/Relatorio_cadop.csv:/docker-entrypoint-initdb.d/Relatorio_cadop.csv
      - ./anexos_operadoras_csv/1T2023.csv:/docker-entrypoint-initdb.d/1T2023.csv
      - ./anexos_operadoras_csv/2T2023.csv:/docker-entrypoint-initdb.d/2T2023.csv
      - ./anexos_operadoras_csv/3T2023.csv:/docker-entrypoint-initdb.d/3T2023.csv
      - ./anexos_operadoras_csv/4T2023.csv:/docker-entrypoint-initdb.d/4T2023.csv
      - ./anexos_operadoras_csv/1T2024.csv:/docker-entrypoint-initdb.d/1T2024.csv
      - ./anexos_operadoras_csv/2T2024.csv:/docker-entrypoint-initdb.d/2T2024.csv
      - ./anexos_operadoras_csv/3T2024.csv:/docker-entrypoint-initdb.d/3T2024.csv
      - ./anexos_operadoras_csv/4T2024.csv:/docker-entrypoint-initdb.d/4T2024.csv

volumes:
  pgdata:
